embeddings {
  tensor_name: "build_num:02500"
  metadata_path: "02500/build_num/metadata.tsv"
  tensor_path: "02500/build_num/tensors.tsv"
}
embeddings {
  tensor_name: "build_type:02500"
  metadata_path: "02500/build_type/metadata.tsv"
  tensor_path: "02500/build_type/tensors.tsv"
}
embeddings {
  tensor_name: "wday:02500"
  metadata_path: "02500/wday/metadata.tsv"
  tensor_path: "02500/wday/tensors.tsv"
}
embeddings {
  tensor_name: "month:02500"
  metadata_path: "02500/month/metadata.tsv"
  tensor_path: "02500/month/tensors.tsv"
}
